//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo09ConsumeWS.SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://Elpepe.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://Elpepe.org/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        private int TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Elpepe.org/", ConfigurationName="SR.MyWSSoap")]
    public interface MyWSSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://Elpepe.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Elpepe.org/HelloWorld", ReplyAction="*")]
        Demo09ConsumeWS.SR.HelloWorldResponse HelloWorld(Demo09ConsumeWS.SR.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Elpepe.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo09ConsumeWS.SR.HelloWorldResponse> HelloWorldAsync(Demo09ConsumeWS.SR.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Elpepe.org/Suma", ReplyAction="*")]
        int Suma(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Elpepe.org/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumaAsync(int x, int y);
        
        // CODEGEN: Generating message contract since element name cliente from namespace http://Elpepe.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Elpepe.org/RegistraCliente", ReplyAction="*")]
        Demo09ConsumeWS.SR.RegistraClienteResponse RegistraCliente(Demo09ConsumeWS.SR.RegistraClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Elpepe.org/RegistraCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Demo09ConsumeWS.SR.RegistraClienteResponse> RegistraClienteAsync(Demo09ConsumeWS.SR.RegistraClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://Elpepe.org/", Order=0)]
        public Demo09ConsumeWS.SR.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Demo09ConsumeWS.SR.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://Elpepe.org/", Order=0)]
        public Demo09ConsumeWS.SR.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Demo09ConsumeWS.SR.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Elpepe.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraCliente", Namespace="http://Elpepe.org/", Order=0)]
        public Demo09ConsumeWS.SR.RegistraClienteRequestBody Body;
        
        public RegistraClienteRequest() {
        }
        
        public RegistraClienteRequest(Demo09ConsumeWS.SR.RegistraClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Elpepe.org/")]
    public partial class RegistraClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo09ConsumeWS.SR.Cliente cliente;
        
        public RegistraClienteRequestBody() {
        }
        
        public RegistraClienteRequestBody(Demo09ConsumeWS.SR.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraClienteResponse", Namespace="http://Elpepe.org/", Order=0)]
        public Demo09ConsumeWS.SR.RegistraClienteResponseBody Body;
        
        public RegistraClienteResponse() {
        }
        
        public RegistraClienteResponse(Demo09ConsumeWS.SR.RegistraClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Elpepe.org/")]
    public partial class RegistraClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Demo09ConsumeWS.SR.Respuesta RegistraClienteResult;
        
        public RegistraClienteResponseBody() {
        }
        
        public RegistraClienteResponseBody(Demo09ConsumeWS.SR.Respuesta RegistraClienteResult) {
            this.RegistraClienteResult = RegistraClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWSSoapChannel : Demo09ConsumeWS.SR.MyWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWSSoapClient : System.ServiceModel.ClientBase<Demo09ConsumeWS.SR.MyWSSoap>, Demo09ConsumeWS.SR.MyWSSoap {
        
        public MyWSSoapClient() {
        }
        
        public MyWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo09ConsumeWS.SR.HelloWorldResponse Demo09ConsumeWS.SR.MyWSSoap.HelloWorld(Demo09ConsumeWS.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Demo09ConsumeWS.SR.HelloWorldRequest inValue = new Demo09ConsumeWS.SR.HelloWorldRequest();
            inValue.Body = new Demo09ConsumeWS.SR.HelloWorldRequestBody();
            Demo09ConsumeWS.SR.HelloWorldResponse retVal = ((Demo09ConsumeWS.SR.MyWSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo09ConsumeWS.SR.HelloWorldResponse> Demo09ConsumeWS.SR.MyWSSoap.HelloWorldAsync(Demo09ConsumeWS.SR.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo09ConsumeWS.SR.HelloWorldResponse> HelloWorldAsync() {
            Demo09ConsumeWS.SR.HelloWorldRequest inValue = new Demo09ConsumeWS.SR.HelloWorldRequest();
            inValue.Body = new Demo09ConsumeWS.SR.HelloWorldRequestBody();
            return ((Demo09ConsumeWS.SR.MyWSSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Suma(int x, int y) {
            return base.Channel.Suma(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SumaAsync(int x, int y) {
            return base.Channel.SumaAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo09ConsumeWS.SR.RegistraClienteResponse Demo09ConsumeWS.SR.MyWSSoap.RegistraCliente(Demo09ConsumeWS.SR.RegistraClienteRequest request) {
            return base.Channel.RegistraCliente(request);
        }
        
        public Demo09ConsumeWS.SR.Respuesta RegistraCliente(Demo09ConsumeWS.SR.Cliente cliente) {
            Demo09ConsumeWS.SR.RegistraClienteRequest inValue = new Demo09ConsumeWS.SR.RegistraClienteRequest();
            inValue.Body = new Demo09ConsumeWS.SR.RegistraClienteRequestBody();
            inValue.Body.cliente = cliente;
            Demo09ConsumeWS.SR.RegistraClienteResponse retVal = ((Demo09ConsumeWS.SR.MyWSSoap)(this)).RegistraCliente(inValue);
            return retVal.Body.RegistraClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Demo09ConsumeWS.SR.RegistraClienteResponse> Demo09ConsumeWS.SR.MyWSSoap.RegistraClienteAsync(Demo09ConsumeWS.SR.RegistraClienteRequest request) {
            return base.Channel.RegistraClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Demo09ConsumeWS.SR.RegistraClienteResponse> RegistraClienteAsync(Demo09ConsumeWS.SR.Cliente cliente) {
            Demo09ConsumeWS.SR.RegistraClienteRequest inValue = new Demo09ConsumeWS.SR.RegistraClienteRequest();
            inValue.Body = new Demo09ConsumeWS.SR.RegistraClienteRequestBody();
            inValue.Body.cliente = cliente;
            return ((Demo09ConsumeWS.SR.MyWSSoap)(this)).RegistraClienteAsync(inValue);
        }
    }
}
