//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo05
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVisita
    {
        public int Id { get; set; }
        public int Tipodocumento { get; set; }
        public string Documento { get; set; }
        public System.DateTime FechaVisita { get; set; }
        public string Nota { get; set; }
        public string Localidad { get; set; }
    }
}
